version: '3.8'

services:
  museum-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum-admin-app
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - MONGODB_URI=mongodb+srv://mbayediao2:mbayediao2003@ecomerce.feavmkc.mongodb.net/musee?retryWrites=true&w=majority&appName=ecomerce
      - SUPABASE_DB_URL=postgresql://postgres.tmhvuxwsmztxqwiaxqja:c0qrXpgZBhkdzWcl@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - NEXT_PUBLIC_SUPABASE_URL=https://tmhvuxwsmztxqwiaxqja.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtaHZ1eHdzbXp0eHF3aWF4cWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDczMzEsImV4cCI6MjA2ODAyMzMzMX0.lKuVf626o4-vTJK7qcqQgbU85EMrL7Qwf-T8DfP1vnQ
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtaHZ1eHdzbXp0eHF3aWF4cWphIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjQ0NzMzMSwiZXhwIjoyMDY4MDIzMzMxfQ.auNOEFfQ61Ye60sPN4XhWxEMsk8AKj4GCbQf72DWr-8
      - SUPABASE_STORAGE_BUCKET=musee
    restart: unless-stopped
    networks:
      - museum-network

networks:
  museum-network:
    driver: bridge
